### ISSUE TITLE
Failure to build on windows 10: Different remotes found on repo F:\PharmaLedger\fgt-workspace\cardinal

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#11]
Low-pit: Only happens on one specific Win10 system:

```
F:\PharmaLedger\fgt-workspace>node -v
v14.16.1

F:\PharmaLedger\fgt-workspace>git status
On branch refs1_architecture_refactor
Your branch is up to date with 'origin/refs1_architecture_refactor'.

F:\PharmaLedger\fgt-workspace>npm run dev-install

> fgt-workspace@0.1.3 dev-install F:\PharmaLedger\fgt-workspace
> node ./bin/mkDevEnv.js && npm install


> fgt-workspace@0.1.3 postinstall F:\PharmaLedger\fgt-workspace
> node bin/version.js && node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "node ./node_modules/octopus/scripts/run"

Wrote version info 612309c-dirty to fgt-dsu-wizard\version.js
Wrote version info 612309c-dirty to apihub-root\index.html
Running in DEVELOPMENT mode
Environment updated accordingly to env file passed as argument.
Preparing to execute cmd node ./node_modules/octopus/scripts/run
Looking for configuration file at path F:\PharmaLedger\fgt-workspace\octopus.json
Action buildWebCardinalComponents was registered.
[Octopus] Start checking dependencies...
[Octopus] Found 22 dependencies...
[Octopus] Running tasks for: [0] cardinal
stdoutXorigin   https://github.com/PharmaLedger-IMI/fgt-workspace (fetch)
origin  https://github.com/PharmaLedger-IMI/fgt-workspace (push)
X, regex /^[origin]*\s*http:\/\/github.com\/privatesky\/cardinal.git[.git]*\s*\(fetch\)/g
F:\PharmaLedger\fgt-workspace\node_modules\octopus\ActionsRegistry.js:271
                        throw new Error(`Different remotes found on repo ${target}`);
                        ^

Error: Different remotes found on repo F:\PharmaLedger\fgt-workspace\cardinal
    at F:\PharmaLedger\fgt-workspace\node_modules\octopus\ActionsRegistry.js:271:31
    at ChildProcess.exithandler (child_process.js:299:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:673:12)
npm WARN fgt-workspace@0.1.3 scripts['server'] should probably be scripts['start'].
```

Augmented console.log at node_modules\octopus\ActionsRegistry.js near 270: 
```
                    let originFetchRegex = new RegExp('^[origin]*\\s*' + src + '[.git]*\\s*\\(fetch\\)', 'g');
                    console.log("stdoutX"+stdout+"X, regex", originFetchRegex);
                    let matchedArr = stdout.match(originFetchRegex)
                    if (!matchedArr) {
                        throw new Error(`Different remotes found on repo ${target}`);
                    }
```

**Comment by joaoluis-pdm** [comment]
It seems the problem only appears with a workspace checked out on eGit 4.11.0.201803080745-r https://wiki.eclipse.org/EGit/FAQ#Where_can_I_find_older_releases_of_EGit.3F
 under an eclipse workspace.
Doing the same with e native "git for windows" checkout, the problem disappeared.

Ignoring the problem.
