### ISSUE TITLE
SimpleShipments being created with non-existent batches

### ISSUE THREAD

**Issue by pccosta-pdm** [PharmaLedger-IMI/fgt-workspace#117]
A GTIN/batch validation must be created before "createSimple" method call when create a SimpleShipment.

**Comment by joaoluis-pdm** [comment]
@pccosta-pdm it is not working.
Please check the following request+error:
```txt
(end) data= {"orderId":"WHS000001-2022-09-02T19:34:11.619Z","requesterId":"WHS000001","shipmentLines":[{"gtin":"00366582505358","batch":"R034995","quantity":100},{"gtin":"00191778005295","batch":"U002114","quantity":100}]} 

/fgt-workspace/fgt-api/managers/SimpleShipmentManager.js:248
                accum[sl.gtin].push(new Batch({
                               ^

TypeError: Cannot read properties of undefined (reading 'push')
    at /fgt-workspace/fgt-api/managers/SimpleShipmentManager.js:248:32
    at /fgt-workspace/fgt-dsu-wizard/services/BatchService.js:85:25
    at returnFunc (/fgt-workspace/fgt-dsu-wizard/services/StatusService.js:76:32)
    at /fgt-workspace/fgt-dsu-wizard/services/StatusService.js:81:36
    at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:42815:20)
    at _readFile (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:774:49)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1360:17
    at waitIfDSUIsRefreshing (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:446:20)
    at Archive.readFile (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:1349:9)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1368:36
    at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:42815:20)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:2122:32
    at Object.Manifest.manifestHandler.getArchiveForPath (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:7658:9)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:2115:25
    at getManifest (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:1280:20)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:2105:13
    at waitIfDSUIsRefreshing (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:446:20)
    at Archive.getArchiveForPath (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:2102:9)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1362:22
    at waitIfDSUIsRefreshing (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:446:20)
    at Archive.readFile (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:1349:9)
    at /fgt-workspace/fgt-dsu-wizard/services/StatusService.js:79:25
    at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:42815:20)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:786:13
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:7331:17
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:6740:28
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:2829:17
    at EncryptionTransformation.undo (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:7812:9)
    at Brick.getRawData (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:2823:30)
    at extractData (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:378:27)
    at Service.brickDataExtractorCallback (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:386:17)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:6731:22
    at checkBrickDataIntegrity (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:6723:17)
    at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:6726:13
    at runnerCallback (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:16512:17)
    at executeForSingleEntry (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:30158:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by pccosta-pdm** [comment]
@joaoluis-pdm fixes made, could you confirm if is ok?
