### ISSUE TITLE
Implement the test case scenarios

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#24]

**Comment by joaoluis-pdm** [comment]
Add Sanofi as an MAH for demonstration purposes.

**Comment by joaoluis-pdm** [comment]
Created release https://github.com/PharmaLedger-IMI/fgt-workspace/releases/tag/v0.8.6

Installing onlu mah-sanofi on fgt-dev-pl based on previous v0.8.5:
```sh
cd fgt-workspace
git pull
cd api/docker
docker-compose build --no-cache mah-sanofi
SIMPLE=fgt-dev.pharmaledger.pdmfc.com DOMAIN=-fgt-dev.pharmaledger.pdmfc.com SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml up -d mah-sanofi
```
If the --no-cache was not given, the mah-sanofi will be built on top of the previous v0.8.5 image,
HEAD detached at 25fa88f3
and will break due to the lack of some new files, such as docker/api/env/mah-sanofi.json

This does not update fgt-workspace, so the Sanofi URL is not present in the index.html

**Comment by joaoluis-pdm** [comment]
Attempting to update fgt-workspace without reseting blockchain:
```sh
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ docker-compose stop fgt-workspace
Stopping fgt-workspace ... done
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ docker-compose rm fgt-workspace
Going to remove fgt-workspace
Are you sure? [yN] y
Removing fgt-workspace ... done
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ docker-compose build --no-cache fgt-workspace
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SIMPLE=fgt-dev.pharmaledger.pdmfc.com DOMAIN=-fgt-dev.pharmaledger.pdmfc.com SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml up -d fgt-workspace
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps -f fgt-workspace> fgt-workspace.log 2>&1
```

I found no errors on the build log of fgt-workspace.

**Comment by joaoluis-pdm** [comment]
Testing deploy of Sanofi ID change to DEV

```sh
pharmaledger@fgt-dev-pl:~/fgt-workspace$ git pull
pharmaledger@fgt-dev-pl:~/fgt-workspace$ cd docker/api/
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ cat env/mah-sanofi.json 
...
  "id": {
    "secret": "MAH196261989",
...
# id is up to date.
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml stop mah-sanofi
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml build mah-sanofi
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml start mah-sanofi
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps -f mah-sanofi 2>&1 | less
```

```sh
...
2022-05-02T14:42:14.627998833Z The wallet couldn't be created. Trying to load with credentials...
2022-05-02T14:42:14.628658179Z Environment for vault fgt-mah-ssapp no-cache
2022-05-02T14:42:14.629691434Z Loading wallet with ssi 3XXka29Q8KUGeWVtxRkGGtuNtSmT7jJd2A4YLCWfMJRZtHRorAjM9Wx7HxZSt2Go5gmp4tnpsS3mrM6Be77gGziTymyQp2i4fgYzftK
2022-05-02T14:42:14.651829846Z wallet Loaded
2022-05-02T14:42:14.651907356Z App fgt-mah-ssapp load with credentials {
2022-05-02T14:42:14.651913286Z   "name": {
2022-05-02T14:42:14.651915915Z     "secret": "Sanofi",
2022-05-02T14:42:14.651918275Z     "public": true
2022-05-02T14:42:14.651920445Z   },
2022-05-02T14:42:14.651922585Z   "id": {
2022-05-02T14:42:14.651925085Z     "secret": "MAH196261986",
2022-05-02T14:42:14.651927365Z     "public": true
2022-05-02T14:42:14.651929425Z   },
2022-05-02T14:42:14.651937985Z   "email": {
2022-05-02T14:42:14.651940105Z     "secret": "sanofi@mah.pharmaledger.com",
2022-05-02T14:42:14.651942275Z     "public": true
2022-05-02T14:42:14.651945765Z   },
2022-05-02T14:42:14.651947705Z   "address": {
2022-05-02T14:42:14.651949855Z     "required": true,
2022-05-02T14:42:14.651951965Z     "public": true
2022-05-02T14:42:14.651954045Z   },
2022-05-02T14:42:14.651956055Z   "pass": {
2022-05-02T14:42:14.651958215Z     "required": true,
2022-05-02T14:42:14.651966685Z     "secret": "This1sSuchAS3curePassw0rd"
2022-05-02T14:42:14.651968915Z   },
2022-05-02T14:42:14.651970865Z   "passrepeat": {
2022-05-02T14:42:14.651972895Z     "required": true,
2022-05-02T14:42:14.651974895Z     "secret": "This1sSuchAS3curePassw0rd"
2022-05-02T14:42:14.651977055Z   }
2022-05-02T14:42:14.651978995Z }.
2022-05-02T14:42:14.651980965Z SSI: [object Object]
2022-05-02T14:42:14.661519570Z Could not initialize base manager Error: Could not get Identity(Path </participant/id/info> not found.)
2022-05-02T14:42:14.662261266Z (node:1198) UnhandledPromiseRejectionWarning: Error: Could not get Identity(Path </participant/id/info> not found.)
2022-05-02T14:42:14.662273376Z     at ErrorWrapper (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:22683:22)
2022-05-02T14:42:14.662276456Z     at createOpenDSUErrorWrapper (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:22713:12)
2022-05-02T14:42:14.662278686Z     at ParticipantManager._err (/fgt-workspace/pdm-dsu-toolkit/services/utils.js:185:39)
2022-05-02T14:42:14.662280826Z     at /fgt-workspace/pdm-dsu-toolkit/managers/BaseManager.js:248:28
2022-05-02T14:42:14.662282876Z     at ParticipantManager._err (/fgt-workspace/pdm-dsu-toolkit/services/utils.js:185:38)
2022-05-02T14:42:14.662285116Z     at /fgt-workspace/pdm-dsu-toolkit/managers/BaseManager.js:240:24
2022-05-02T14:42:14.662287326Z     at ParticipantManager._err (/fgt-workspace/pdm-dsu-toolkit/services/utils.js:185:38)
...
```
```sh
pharmaledger@fgt-dev-pl:~$ docker exec -it mah-sanofi /bin/bash
root@mah-sanofi:/# cd fgt-workspace/docker/api/
root@mah-sanofi:/fgt-workspace/docker/api# cat env/mah-sanofi.json 
...
  "id": {
    "secret": "MAH196261986",
...
```

The old ID was kept. So this docker-compose build did work as expected. Docker image was not updated.

**Comment by joaoluis-pdm** [comment]
Try again to rebuild mah-sanofi with --no-cache:
```sh
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml stop mah-sanofi
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml build mah-sanofi
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml start mah-sanofi
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps -f mah-sanofi 2>&1 | less
```

(The build step took a lot longer).

**Comment by joaoluis-pdm** [comment]
Trying again... after another freeze attempt.

Try again to rebuild mah-sanofi with --no-cache:
```sh
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ git pull
remote: Enumerating objects: 2, done.
remote: Counting objects: 100% (2/2), done.
remote: Total 2 (delta 1), reused 2 (delta 1), pack-reused 0
Unpacking objects: 100% (2/2), 235 bytes | 235.00 KiB/s, done.
From https://github.com/PharmaLedger-IMI/fgt-workspace
   08b6b119..c3b78a50  master     -> origin/master
Updating 08b6b119..c3b78a50
Fast-forward
 octopus-freeze.json | 1 +
 1 file changed, 1 insertion(+)

pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml stop mah-sanofi
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml build --no-cache mah-sanofi
...
> fgt-workspace@0.9.3 postinstall /fgt-workspace
> node ./node_modules/octopus/scripts/setEnv --file=../../../env.json "npm run do-install"

Running in STABLE (FREEZED) mode
Preparing to set on process.env the following info: {
  PSK_TMP_WORKING_DIR: 'tmp',
  PSK_CONFIG_LOCATION: '../apihub-root/external-volume/config',
  DEV: false
}
Environment updated accordingly to env file passed as argument.
Preparing to execute cmd npm run do-install

> fgt-workspace@0.9.3 do-install /fgt-workspace
> node ./node_modules/octopus/scripts/ensureFreezeState.js && node ./bin/version.js && node ./node_modules/octopus/scripts/run

Wrote version info v0.9.3-4-gc3b78a50 to fgt-dsu-wizard/version.js
Wrote version info v0.9.3-4-gc3b78a50 to apihub-root/index.html
Looking for configuration file at path /fgt-workspace/octopus-freeze.json
...
... THE FREEZE COMMIT SEEMS CORRECT!
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml start mah-sanofi
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps -f mah-sanofi 2>&1 | less
...
2022-05-02T15:36:16.604553390Z wallet Loaded
2022-05-02T15:36:16.604707399Z App fgt-mah-ssapp load with credentials {
2022-05-02T15:36:16.604714589Z   "name": {
2022-05-02T15:36:16.604717229Z     "secret": "Sanofi",
2022-05-02T15:36:16.604719609Z     "public": true
2022-05-02T15:36:16.604721959Z   },
2022-05-02T15:36:16.604724129Z   "id": {
2022-05-02T15:36:16.604726219Z     "secret": "MAH196261986",
2022-05-02T15:36:16.604728429Z     "public": true
2022-05-02T15:36:16.604730469Z   },
2022-05-02T15:36:16.604732409Z   "email": {
2022-05-02T15:36:16.604741148Z     "secret": "sanofi@mah.pharmaledger.com",
2022-05-02T15:36:16.604743438Z     "public": true
2022-05-02T15:36:16.604745428Z   },
2022-05-02T15:36:16.604747368Z   "address": {
2022-05-02T15:36:16.604749408Z     "required": true,
2022-05-02T15:36:16.604751518Z     "public": true
2022-05-02T15:36:16.604753548Z   },
2022-05-02T15:36:16.604755498Z   "pass": {
2022-05-02T15:36:16.604757518Z     "required": true,
2022-05-02T15:36:16.604759718Z     "secret": "This1sSuchAS3curePassw0rd"
2022-05-02T15:36:16.604761928Z   },
2022-05-02T15:36:16.604763958Z   "passrepeat": {
2022-05-02T15:36:16.604765998Z     "required": true,
2022-05-02T15:36:16.604768028Z     "secret": "This1sSuchAS3curePassw0rd"
2022-05-02T15:36:16.604770138Z   }
2022-05-02T15:36:16.604772098Z }.
2022-05-02T15:36:16.604774108Z SSI: [object Object]
2022-05-02T15:36:16.614008377Z Could not initialize base manager Error: Could not get Identity(Path </participant/id/info> not found.)
2022-05-02T15:36:16.614766572Z (node:1204) UnhandledPromiseRejectionWarning: Error: Could not get Identity(Path </participant/id/info> not found.)
2022-05-02T15:36:16.614779822Z     at ErrorWrapper (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:22683:22)
...
...

Fail again!

**Comment by joaoluis-pdm** [comment]
Trying again with docker-compose rm, and docker-compose up -d --force-recreate.

```
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml stop mah-sanofi
Stopping mah-sanofi ... done
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml rm
Going to remove mah-sanofi
Are you sure? [yN] y
Removing mah-sanofi ... done
pharmaledger@fgt-dev-pl:~/fgt-workspace/docker/api$ SWAGGER=-fgt-dev.pharmaledger.pdmfc.com PROTOCOL=https COMMAND= docker-compose -f docker-compose.yml -f docker-compose-eth.yml up -d --force-recreate mah-sanofi 2>&1 | tee upsanofi.log
```
