### ISSUE TITLE
v0.5.0 MaxListenersExceededWarning / errors deploying while there are browsers using the FGT wallets

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#25]
Before even running npm run environment-test, we have error:
```
(node:1093) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

Diagnostic:

With haproxy on:
```
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps fgt > fgt.log 2>&1 
pharmaledger@fgt-dev-pl:~$ less fgt.log
...
2021-09-06T14:18:57.921594927Z [API-HUB] listening on port :8080 and ready to receive requests.
2021-09-06T14:18:57.921597728Z 
2021-09-06T14:18:58.546383204Z undefined:8080 - [2021-09-06T14:18:58.530Z] GET:/mq/receive-message/did:demo:MAH135315170 500 3.868ms
2021-09-06T14:18:58.547681052Z undefined:8080 - [2021-09-06T14:18:58.547Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.36ms
2021-09-06T14:18:58.548591417Z 192.168.13.5:8080 - [2021-09-06T14:18:58.548Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.193ms
2021-09-06T14:18:58.549074525Z 192.168.13.5:8080 - [2021-09-06T14:18:58.548Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.157ms
2021-09-06T14:19:00.529263307Z 192.168.13.5:8080 - [2021-09-06T14:19:00.528Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.198ms
2021-09-06T14:19:00.529605048Z 192.168.13.5:8080 - [2021-09-06T14:19:00.529Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.205ms
2021-09-06T14:19:02.528358208Z 192.168.13.5:8080 - [2021-09-06T14:19:02.527Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.404ms
2021-09-06T14:19:02.529287195Z 192.168.13.5:8080 - [2021-09-06T14:19:02.528Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.261ms
2021-09-06T14:19:04.527204506Z 192.168.13.5:8080 - [2021-09-06T14:19:04.526Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.226ms
2021-09-06T14:19:04.527452742Z 192.168.13.5:8080 - [2021-09-06T14:19:04.527Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.129ms
2021-09-06T14:19:06.527772915Z 192.168.13.5:8080 - [2021-09-06T14:19:06.527Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.452ms
2021-09-06T14:19:06.528336348Z 192.168.13.5:8080 - [2021-09-06T14:19:06.528Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.148ms
2021-09-06T14:19:08.534583138Z 192.168.13.5:8080 - [2021-09-06T14:19:08.533Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.445ms
2021-09-06T14:19:08.535099308Z 192.168.13.5:8080 - [2021-09-06T14:19:08.534Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.275ms
2021-09-06T14:19:10.539753304Z 192.168.13.5:8080 - [2021-09-06T14:19:10.539Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.427ms
2021-09-06T14:19:10.540734351Z 192.168.13.5:8080 - [2021-09-06T14:19:10.540Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.344ms
2021-09-06T14:19:12.541304916Z 192.168.13.5:8080 - [2021-09-06T14:19:12.540Z] GET:/mq/receive-message/did:demo:MAH135315170 500 0.423ms
2021-09-06T14:19:12.541933805Z 192.168.13.5:8080 - [2021-09-06T14:19:12.541Z] GET:/mq/receive-message/did:demo:PHAZCGVW7A7 500 0.329ms
2021-09-06T14:19:14.538792217Z (node:49) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 close listeners added to [Socket]. Use emitter.setMaxListeners() to increase limit
2021-09-06T14:19:14.538826408Z (Use `node --trace-warnings ...` to show where the warning was created)
...
2021-09-06T14:21:23.194178294Z Caught event type [uncaughtException]. Shutting down... uncaughtException Error [ERR_STREAM_WRITE_AFTER_END]: write after end
2021-09-06T14:21:23.194187414Z     at writeAfterEnd (_http_outgoing.js:668:15)
2021-09-06T14:21:23.194190214Z     at write_ (_http_outgoing.js:680:5)
2021-09-06T14:21:23.194192444Z     at ServerResponse.write (_http_outgoing.js:661:15)
2021-09-06T14:21:23.194194634Z     at /fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:3492:8
2021-09-06T14:21:23.194196824Z     at deliverMessage (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:4443:5)
2021-09-06T14:21:23.194211804Z     at NotificationsManager.sendMessage (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:4504:11)
2021-09-06T14:21:23.194214184Z     at /fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:3451:24
2021-09-06T14:21:23.194216314Z     at IncomingMessage.<anonymous> (/fgt-workspace/privatesky/psknode/bundles/pskWebServer.js:6344:9)
2021-09-06T14:21:23.194218714Z     at IncomingMessage.emit (events.js:327:22)
2021-09-06T14:21:23.194220794Z     at endReadableNT (internal/streams/readable.js:1327:12)
2021-09-06T14:21:23.194222984Z     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2021-09-06T14:21:23.194225154Z   code: 'ERR_STREAM_WRITE_AFTER_END'
2021-09-06T14:21:23.194246514Z }
```

The MaxListenersExceededWarning occurs early and causes api-hub to shutdown.

Workaround so far: Shutdown (inhibit fgt-dev) site on haproxy during the docker startup + npm build-all + npm run environment-test and run it again later.

```
root@haproxy:~# vi /etc/haproxy/haproxy.cfg 
-------- COMMENT BY PREFIXING WITH #
       #use_backend fgt-dev-pl if { hdr(host) -i fgt.dev.pharmaledger.pdmfc.com }
       #use_backend fgt-dev-pl if { hdr(host) -i fgt-dev.pharmaledger.pdmfc.com }
--------

root@haproxy:~# systemctl reload haproxy ; less /var/log/haproxy.log

```

With haproxy stopped, re-deployed the docker image, and watch log again:
```
pharmaledger@fgt-dev-pl:~$ docker logs --timestamps fgt > fgt2.log 2>&1 
```
Workaround seems to work.
Enabled haproxy again. (remove the # prefix for fgt-dev sites, and reload haproxy).

**Comment by joaoluis-pdm** [comment]
There seems to be no way to disable/enable published ports at runtime, without stopping/restarting the docker...

https://stackoverflow.com/questions/19335444/how-do-i-assign-a-port-mapping-to-an-existing-docker-container

**Comment by TiagoV-PDMFC** [comment]
Since v0.8.0 this is no longer an issue (a decent health check solves this issue)
