### ISSUE TITLE
Connect system to blockchain node

### ISSUE THREAD

**Issue by TiagoV-PDMFC** [PharmaLedger-IMI/fgt-workspace#30]
Deploy blockchain environment and connect fgt to it to simulate 'real-world' behaviour.

connects to issue #28

**Comment by joaoluis-pdm** [comment]
![image](https://user-images.githubusercontent.com/77448470/155319427-e9a3ddae-2542-4da1-9269-0f8b60e6cd89.png)
![image](https://user-images.githubusercontent.com/77448470/155319616-2fe61a4f-4a58-4c06-a48e-4cb390d3781c.png)

**Comment by joaoluis-pdm** [comment]
```
[10h17](https://opendsu.slack.com/archives/G01DZPK1212/p1645697827305079)
[João Luís (PDM)](https://app.slack.com/team/U01DMGU0W5T) Today I have this error in ethAdaptor 62c61b45c9ff44900d31d79d1efc803e024c3589 and psk-release a34b39909b21db33b8219a1e2a88226bdba135d9 - ReporterError: length octect is too long at: (shallow)finished get anchors : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BvYQW3X48Wj6FGtKXpoV8PrfQe2HVgxVT5oGG5krPy43zkSu7FdNVWVDr3tJ9QcrUCKeHSTrZ7ANfZJYsiyqXbHogt9FonaB7PNPeiX76TCL24qapmGvBB9RC5PDH []
response getAnchorVersions 200 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BvYQW3X48Wj6FGtKXpoV8PrfQe2HVgxVT5oGG5krPy43zkSu7FdNVWVDr3tJ9QcrUCKeHSTrZ7ANfZJYsiyqXbHogt9FonaB7PNPeiX76TCL24qapmGvBB9RC5PDH []
body received :  {
  hash: {
    newHashLinkSSI: 'HxMN6F7bEr3M14JMPPgGVkXwUyAf6zQtFMYFhT4AVxmNmdQJEbRbEj9pZBwb3uUip5HHYeMSgYW9UwRiqyKpzWmPydegEJCj69irmRkor1goGxkTTAfaFtPQLQEF43ZUVbV3pYEHttZXKDaEZNNWkudsNymqVUhjAUvPxRoSJsDAFCrtujyUCJfy7f9hup51PtuzZSgzFdAD8R3LuLJD2rgQGrirDjLaq2LXRgBpvwh',
    lastHashLinkSSI: null
  },
  digitalProof: {
    signature: 'B4RnxF5i3fCw9QkrKLhWAY2iRQwmnGbBcGnbXWDVhUs8YNRcanRMG163KNF8FGEUY2e3yhpL6fViH5AV8ZwB4qx9Z',
    publicKey: 'PZodA79Fn12o38w5DafpYWj7KzPGBycafLUfj32vXWnuo2m9ULNrLd3LbkJU3YR45Gft1KKdrq5iTTHaNG6c6faL'
  },
  zkp: ''
}
Decoded from 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BvYQW3X48Wj6FGtKXpoV8PrfQe2HVgxVT5oGG5krPy43zkSu7FdNVWVDr3tJ9QcrUCKeHSTrZ7ANfZJYsiyqXbHogt9FonaB7PNPeiX76TCL24qapmGvBB9RC5PDH  into KEYSSI :  [
  'ssi',
  'sza',
  'traceability',
  '',
  'PZodA79Fn12o38w5DafpYWj7KzPGBycafLUfj32vXWnuo2m9ULNrLd3LbkJU3YR45Gft1KKdrq5iTTHaNG6c6faL',
  'v0'
]
public key RAW :  PZodA79Fn12o38w5DafpYWj7KzPGBycafLUfj32vXWnuo2m9ULNrLd3LbkJU3YR45Gft1KKdrq5iTTHaNG6c6faL
prefixed pub key :  0x0468a9aab314bec48a1c2f8646d0105eb117e148b7dbf719568c78e72f888996e32ca02301a2d95c4a77c87fb17ed46c0de406bbfb5a23ef65cf9e3f5a6774763d
signature :  B4RnxF5i3fCw9QkrKLhWAY2iRQwmnGbBcGnbXWDVhUs8YNRcanRMG163KNF8FGEUY2e3yhpL6fViH5AV8ZwB4qx9Z
------------------------------------------------------
2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BvYQW3X48Wj6FGtKXpoV8PrfQe2HVgxVT5oGG5krPy43zkSu7FdNVWVDr3tJ9QcrUCKeHSTrZ7ANfZJYsiyqXbHogt9FonaB7PNPeiX76TCL24qapmGvBB9RC5PDH
ReporterError: length octect is too long at: (shallow)
    at DecoderBuffer.error (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:32788:11)
    at derDecodeLen (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:35613:16)
    at DERNode.decodeTag [as _decodeTag] (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:35389:13)
    at DERNode.decode [as _decode] (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:32447:23)
    at DERNode.decode [as _decode] (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:32389:47)
    at ECPrivateKey.decode (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:35359:20)
    at Entity.decode (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:31970:32)
    at Object.decodeDERIntoASN1ETH (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:36192:31)
    at PskCrypto.decodeDerToASN1ETH (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:31806:70)
    at Object.convertDerSignatureToASN1 (/ePI-workspace/privatesky/psknode/bundles/openDSU.js:16279:33)
    at Object.convertDerSignatureToASN1 (/ePI-workspace/ethadapter/EthAdapter/utils/opendsuutils.js:20:26)
    at getSignatureForSmartContract (/ePI-workspace/ethadapter/EthAdapter/controllers/addAnchor.js:114:38)
    at /ePI-workspace/ethadapter/EthAdapter/controllers/addAnchor.js:59:31
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at /ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:281:22
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:360:14)
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:416:3)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.<anonymous> (/ePI-workspace/ethadapter/EthAdapter/webserver.js:25:9)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: ''
}
------------------------------------------------------
finished get anchors : 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BvYQW3X48Wj6FGtKXpoV8PrfQe2HVgxVT5oGG5krPy43zkSu7FdNVWVDr3tJ9QcrUCKeHSTrZ7ANfZJYsiyqXbHogt9FonaB7PNPeiX76TCL24qapmGvBB9RC5PDH [] (editado)
```

**Comment by joaoluis-pdm** [comment]
![image](https://user-images.githubusercontent.com/77448470/157230037-fad7ce86-ed17-428c-9870-587ebe057d70.png)

**Comment by joaoluis-pdm** [comment]
```txt
[João Luís (PDM)](https://app.slack.com/team/U01DMGU0W5T)  [há 4 horas](https://opendsu.slack.com/archives/G01DZPK1212/p1647528120674039?thread_ts=1647452936.964729&cid=G01DZPK1212)
Just to update that we managed a working combination with:psk-release      6f5ad4c50f6eea9589a5eaeaf056767c4a43d2b8     Thu Feb 17 11:50:54 2022 +0200
ethadapter       a63308f5ffe1182311dc10b6e49473727b8acc99      Mon Mar 14 15:45:02 2022 +0200
epi-workspace adac48270eef5629ab2134ea3fc50be2da5e9f02      Wed Mar 16 17:05:55 2022 +0200So please consider the above questions overcome (by trial and error :-)

Spoke too soon! :decepcionado:I am getting in ethAdapter the error:TypeError: anchorFactory.methods.getAnchorVersions is not a function
    at getVersions (/ePI-workspace/ethadapter/EthAdapter/anchoring/getVersionsAnchorSmartContract.js:3:27)
    at /ePI-workspace/ethadapter/EthAdapter/controllers/getVersions.js:6:63
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at /ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:281:22
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:360:14)
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:416:3)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.<anonymous> (/ePI-workspace/ethadapter/EthAdapter/webserver.js:25:9)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)Any ideas ? Go forward/backwards with versions ? (editado) 
    
    Even if I replace (in the ethadapter) the implementation ofethadapter/EthAdapter/anchoring/getVersionsAnchorSmartContract.jswith the existingethadapter/EthAdapter/anchoring/getAllVersionsSmartContract.jsit passes that error.But later will fail on (editado) 

[João Luís (PDM)](https://app.slack.com/team/U01DMGU0W5T)  [há 3 minutos](https://opendsu.slack.com/archives/G01DZPK1212/p1647543855510719?thread_ts=1647452936.964729&cid=G01DZPK1212)
/addAnchor/2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoDW1gpEY1kvTCYzPFacnzBmj9kBtz8zaQ4NPFUkZNDGmGcNHKgAdNfzVw1y45W8vxDhmEPopZ9kDCwkCtcPdtP7MAnNtFb4rmnYoyinULMzX8KaUAn3YgdBewBm {
  hash: {
    newHashLinkSSI: '4qnrBhooj78L2psbyjJ44LqFA4DA5wVRmv8oEbHF4yd9XAmrYKFVeSnPjCNVb7F6seKGR6BtapYTsTVLx2yMJevnu6PtohEau2694UgRNeeWbYJzbzZhvpiC37Eh2ziWQLeKfSSwdTJSKh1PTCnqK8cRLV12tRMyTdbVH7AnQ2zi5fqdQj2GuUy8YpgP6HVjyTBwkuP7brpLmb5pwZL7EF1vfyrXus5Q7VVUgkFUQo',
    lastHashLinkSSI: null
  },
  digitalProof: {
    signature: '30Egm52sBEtQTggn6JyG2wLDdF8PeXaN2iJTIWyz1itSJjbVsMjYeyp2zLZ0symMZ0UUxPGvBUid4MbcG2V6wBw=',
    publicKey: 'BD6qfaLJ+5IP7OfGWvWVOCprLYG/YNb7F88Z4J8gIepFm95CILlc7OMLN4sKZwjQfcE4ViMjwzCOQ8pSdMQHVVs='
  },
  zkp: ''
}
body received :  {
  hash: {
    newHashLinkSSI: '4qnrBhooj78L2psbyjJ44LqFA4DA5wVRmv8oEbHF4yd9XAmrYKFVeSnPjCNVb7F6seKGR6BtapYTsTVLx2yMJevnu6PtohEau2694UgRNeeWbYJzbzZhvpiC37Eh2ziWQLeKfSSwdTJSKh1PTCnqK8cRLV12tRMyTdbVH7AnQ2zi5fqdQj2GuUy8YpgP6HVjyTBwkuP7brpLmb5pwZL7EF1vfyrXus5Q7VVUgkFUQo',
    lastHashLinkSSI: null
  },
  digitalProof: {
    signature: '30Egm52sBEtQTggn6JyG2wLDdF8PeXaN2iJTIWyz1itSJjbVsMjYeyp2zLZ0symMZ0UUxPGvBUid4MbcG2V6wBw=',
    publicKey: 'BD6qfaLJ+5IP7OfGWvWVOCprLYG/YNb7F88Z4J8gIepFm95CILlc7OMLN4sKZwjQfcE4ViMjwzCOQ8pSdMQHVVs='
  },
  zkp: ''
}
Decoded from 2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoDW1gpEY1kvTCYzPFacnzBmj9kBtz8zaQ4NPFUkZNDGmGcNHKgAdNfzVw1y45W8vxDhmEPopZ9kDCwkCtcPdtP7MAnNtFb4rmnYoyinULMzX8KaUAn3YgdBewBm  into KEYSSI :  [
  'ssi',
  'sza',
  'traceability',
  '',
  'BD6qfaLJ+5IP7OfGWvWVOCprLYG/YNb7F88Z4J8gIepFm95CILlc7OMLN4sKZwjQfcE4ViMjwzCOQ8pSdMQHVVs=',
  'v0'
]
------------------------------------------------------
2eg3XSYLuY9m6WqTiuqrGAy3mMB9s3BkoDW1gpEY1kvTCYzPFacnzBmj9kBtz8zaQ4NPFUkZNDGmGcNHKgAdNfzVw1y45W8vxDhmEPopZ9kDCwkCtcPdtP7MAnNtFb4rmnYoyinULMzX8KaUAn3YgdBewBm
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (buffer.js:330:9)
    at /ePI-workspace/ethadapter/EthAdapter/controllers/addAnchor.js:35:43
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/layer.js:95:5)
    at /ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:281:22
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:360:14)
    at param (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:371:14)
    at Function.process_params (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:416:3)
    at next (/ePI-workspace/ethadapter/EthAdapter/node_modules/express/lib/router/index.js:275:10)
    at IncomingMessage.<anonymous> (/ePI-workspace/ethadapter/EthAdapter/webserver.js:26:9)
    at IncomingMessage.emit (events.js:314:20)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
------------------------------------------------------    

```

ethAdapter+psk-release seems just to unstable to do anything with it.

**Comment by joaoluis-pdm** [comment]
After updating psk-release, seems to work with [cda1a9e498cc4fba10006d5f4c08c0554e8f4762](https://github.com/PharmaLedger-IMI/blockchain-node-workspace/tree/cda1a9e498cc4fba10006d5f4c08c0554e8f4762)

**Comment by joaoluis-pdm** [comment]
Spoke too soon. Failed wsCreateStuff
```txt
Sleep 2000ms
http PUT {"path":"/traceability/shipment/update/MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758","method":"PUT","headers":{"content-type":"application/json","content-length":82},"hostname":"api-mah-msd.localhost","port":"8080"} {"status":"delivered","extraInfo":"Delivered in good condition by a test script!"}
res {
  shipmentId: 'MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758',
  orderId: 'WHS000001-2022-03-18T12:11:26.231Z',
  requesterId: 'WHS000001',
  senderId: 'MAH136366355',
  status: {
    status: 'delivered',
    log: [
      'MAH136366355 1647605496725 set status to created',
      'MAH136366355 1647605542271 updated status from created to pickup',
      'MAH136366355 1647605548503 updated status from pickup to transit',
      'MAH136366355 1647605554867 updated status from transit to delivered'
    ],
    extraInfo: { pickup: [Array], transit: [Array], delivered: [Array] }
  },
  shipmentLines: [
    {
      gtin: '00366582505358',
      batch: 'R034995',
      quantity: 100,
      senderId: 'MAH136366355',
      requesterId: 'WHS000001',
      status: [Object],
      createdOn: 1647605486249
    },
    {
      gtin: '00191778005295',
      batch: 'U002114',
      quantity: 100,
      senderId: 'MAH136366355',
      requesterId: 'WHS000001',
      status: [Object],
      createdOn: 1647605486249
    }
  ]
}
Sleep 2000ms
http PUT {"path":"/traceability/shipment/update/MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758","method":"PUT","headers":{"content-type":"application/json","content-length":80},"hostname":"api-whs1.localhost","port":"8080"} {"status":"received","extraInfo":"Received in good condition by a test script!"}
res {
  status: 400,
  error: 'Bad Request',
  message: 'Missing record in table simpleShipments and key MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758(Path </mydb/simpleShipments/records/MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758> not found.)'
}
/export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:505
        throw Error("shipment/update "+shipmentId+" reply has no shipmentId: "+JSON.stringify(resUReceived));
              ^

Error: shipment/update MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758 reply has no shipmentId: {"status":400,"error":"Bad Request","message":"Missing record in table simpleShipments and key MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758(Path </mydb/simpleShipments/records/MAH136366355-WHS000001-WHS000001-2022-03-18T12:11:26.231Z-16476054862483241758> not found.)"}
    at shipmentCreateAndDeliver (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:505:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async shipmentsCreateTest (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:552:5)
    at async shipmentsCreate (/export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:620:9)
    at async /export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:799:5
```
[mahAndWhs1Log.zip](https://github.com/PharmaLedger-IMI/fgt-workspace/files/8304792/mahAndWhs1Log.zip)

**Comment by joaoluis-pdm** [comment]
Analyzing with @TiagoV-PDMFC  and @pccosta-pdm  it seems that the problem above is just a very hight delay (>60 seconds) between a shipment is updated on the MAH and propagated to the WHS.

**Comment by joaoluis-pdm** [comment]
haproxy server timeout raised to 5min
```txt
backend fgt-dev-pl
        option forwardfor
        timeout server 5m
        server fgt-dev-pl fgt-dev-pl:8080
```

**Comment by joaoluis-pdm** [comment]
Timings comparison:

[timingsEth.log](https://github.com/PharmaLedger-IMI/fgt-workspace/files/8306897/timingsEth.log)

[timingsLocal.log](https://github.com/PharmaLedger-IMI/fgt-workspace/files/8306909/timingsLocal.log)

The "timingsEth.log" is from fgt-dev-pl and "timingsLocal.log" is from a laptop with SSD, so they are not directly comparable.

But you get +/- between 10 and 20 times slower without ETH.

**Comment by joaoluis-pdm** [comment]
Screenshot 2 days uptime.
![image](https://user-images.githubusercontent.com/77448470/159240857-2545cc59-ecd7-4bdd-a01c-58ecfb2b3fa4.png)

**Comment by joaoluis-pdm** [comment]
For memory leak purposes, the memory usage after re-creating the blockchain-node-workspace and all fgt dockers (without running wsCreateStuff):

![image](https://user-images.githubusercontent.com/77448470/159744305-2f83688c-0c98-460c-bf17-d7575c99add7.png)

**Comment by joaoluis-pdm** [comment]
Done for https://github.com/PharmaLedger-IMI/blockchain-node-workspace/releases/tag/v0.4.2

The BC v0.4.2 is unstable, but let that solve itslef in its own issue https://github.com/PharmaLedger-IMI/blockchain-node-workspace/issues/5

**Comment by joaoluis-pdm** [comment]
Also connect the system to hlf.

As hlf is using a distinct IP address 172.16.0.9, a distinct traceability.json domain patch is required.

**Comment by joaoluis-pdm** [comment]
As the change https://github.com/PharmaLedger-IMI/blockchain-hf-workspace/commit/6eeda211722cfaf711009209726443c3a221bda5 allows the hlf-adapter to run at the same private IP address 172.16.16.16:3000 there is no need to change fgt.

**Comment by joaoluis-pdm** [comment]
Branch [refs30_dockerSeqStartup](https://github.com/PharmaLedger-IMI/fgt-workspace/tree/refs30_dockerSeqStartup) was created to test the startup of all the docker containers in sequence.

This was done to attempt workaround of https://github.com/PharmaLedger-IMI/blockchain-hf-workspace/issues/3

**Comment by joaoluis-pdm** [comment]
Branch [refs30_dockerSeqStartup](https://github.com/PharmaLedger-IMI/fgt-workspace/tree/refs30_dockerSeqStartup) was created to test the startup of all the docker containers in sequence.

This was done to attempt workaround of https://github.com/PharmaLedger-IMI/blockchain-hf-workspace/issues/3

**Comment by joaoluis-pdm** [comment]
qbn-net has been renamed to dsu-bc-net in https://github.com/PharmaLedger-IMI/blockchain-node-workspace/ (since v0.4.5) and in https://github.com/PharmaLedger-IMI/blockchain-hlf-workspace

Rename qbn-net to dsu-bc-net

**Comment by joaoluis-pdm** [comment]
HyperLedger experiments where suspended on 2022-08-19 due to https://github.com/PharmaLedger-IMI/blockchain-hlf-workspace/issues/6

fgt-dev is now running with simulated blockchain.

**Comment by joaoluis-pdm** [comment]
https://github.com/PharmaLedger-IMI/blockchain-hlf-workspace/issues/6 closed. fgt-dev back to hlf blockchain.

**Comment by joaoluis-pdm** [comment]
Quoted from: https://github.com/PharmaLedger-IMI/blockchain-node-workspace/issues/5#issuecomment-1245393626

> On OpenDSU acceleration meeting 2022-09-13, it was presented that this problem seems due to some sort of GoQuorum limitation/protection.
> 2 kinds of workaround will be provided:
> 1 - OBA (Optimistic Blockchain Anchoring)
> 2 - throttling at the eth-adapter (client will have do deal with errors and retry...)
