### ISSUE TITLE
GoQuorum blockchain recovery scenario

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#78]
```txt
On the GoQuorum side, an ethAdapter error of:
2022-05-10T14:37:36.852096314Z Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
2022-05-10T14:37:36.852120534Z     at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
2022-05-10T14:37:36.852127654Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:419:49
2022-05-10T14:37:36.852132354Z     at runMicrotasks (<anonymous>)
2022-05-10T14:37:36.852137204Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2022-05-10T14:37:36.852141624Z   receipt: undefined
2022-05-10T14:37:36.852145884Z }
2022-05-10T14:37:36.852150014Z ------------------------------------------------------
2022-05-10T14:37:36.852154334Z response appendAnchor 428. Error :  Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!

means that something should be wrong with quorum nodes, right ?Hard to see what is going on on the goQuorum side......

2022-05-10T11:13:06.380453853Z WARN [05-10|11:13:06.380] Head headers broke chain ordering        peer=30b9dc94300d274a index=0 requested=574699 received=574702
2022-05-10T11:13:06.380558402Z WARN [05-10|11:13:06.380] Synchronisation failed, dropping peer    peer=30b9dc94300d274a err="retrieved hash chain is invalid: head headers broke chain ordering"
2022-05-10T11:16:54.002600290Z WARN [05-10|11:16:54.002] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=574928 err="future message" number=574929 hash="52186e…4d9a2d"
...
2022-05-10T14:22:33.747296565Z WARN [05-10|14:22:33.746] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=585924 err="future message" number=585925 hash="42514d…a440c7"
2022-05-10T14:24:52.443293869Z WARN [05-10|14:24:52.443] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=586060 err="future message" number=586061 hash="ad20c5…a61999"
2022-05-10T14:25:00.026570123Z WARN [05-10|14:25:00.026] Served eth_call                          conn=172.16.16.16:43320 reqid=27113 t=11.775304821s err="execution aborted (timeout = 5s)"
2022-05-10T14:40:48.007568639Z WARN [05-10|14:40:48.002] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=587004 err="future message"                   number=587005 hash="ed00fb…d2a3f8"
2022-05-10T14:52:59.318647172Z WARN [05-10|14:52:59.318] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=587723 err="future message"                   number=587724 hash="c853e9…ede1bf"
...
```

Symptoms: Trying to create a new product... and it fails.

fgt-workspace:

```txt
2022-05-11T13:29:27.412290929Z [POST] http://172.16.16.16:3000/createAnchor/29fgyfS13tr4gjabfTYGXNFDRPzLXquER412vXvsUzZ3EygdGJMpcDiSGJPirWZsp2ASPcdrxVumS4UnsXiBZjbf64Ry28P/G73iPJYaFmfMiBcFYy1vLzEqPxiV3jhT6ybQbGNyRCBzh8HuhnnRuY2UXoZze6hy9Vn8Z2oYLXs3G5E1ccB7LBUYpJvv3 Error: socket hang up
2022-05-11T13:29:27.412380779Z     at connResetException (internal/errors.js:607:14)
2022-05-11T13:29:27.412506168Z     at Socket.socketOnEnd (_http_client.js:493:23)
2022-05-11T13:29:27.412527908Z     at Socket.emit (events.js:327:22)
2022-05-11T13:29:27.412576707Z     at endReadableNT (internal/streams/readable.js:1327:12)
2022-05-11T13:29:27.412592987Z     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2022-05-11T13:29:27.412612107Z   code: 'ECONNRESET'
2022-05-11T13:29:27.412617307Z }
2022-05-11T13:29:27.412634367Z Error: socket hang up
2022-05-11T13:29:27.412639137Z     at connResetException (internal/errors.js:607:14)
2022-05-11T13:29:27.412643857Z     at Socket.socketOnEnd (_http_client.js:493:23)
2022-05-11T13:29:27.412648437Z     at Socket.emit (events.js:327:22)
2022-05-11T13:29:27.412653107Z     at endReadableNT (internal/streams/readable.js:1327:12)
2022-05-11T13:29:27.412679357Z     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
2022-05-11T13:29:27.412683877Z   code: 'ECONNRESET'
2022-05-11T13:29:27.412687887Z }
2022-05-11T13:29:27.412696617Z 172.16.63.64:8080 - [2022-05-11T13:27:27.409Z] PUT:/anchor/traceability/create-anchor/29fgyfS13tr4gjabfTYGXNFDRPzLXquER412vXvsUzZ3EygdGJMpcDiSGJPirWZsp2ASPcdrxVumS4UnsXiBZjbf64Ry28P/G73iPJYaFmfMiBcFYy1vLzEqPxiV3jhT6ybQbGNyRCBzh8HuhnnRuY2UXoZze6hy9Vn8Z2oYLXs3G5E1ccB7LBUYpJvv3 500 120,002.792ms
```

ethAdapter

```txt
...
2022-05-11T13:27:27.413740277Z finished get anchors : ssi:cza:traceability:831i3LKa82i8kQgaxfb5hR47WpujVGCu8owyyBjZ1Bj7::v0 []
2022-05-11T13:40:00.003003049Z {
2022-05-11T13:40:00.003038148Z   anchorID: 'ssi:cza:traceability:831i3LKa82i8kQgaxfb5hR47WpujVGCu8owyyBjZ1Bj7::v0',
2022-05-11T13:40:00.003041848Z   newAnchorValue: 'ssi:hl:traceability:7PMBFGe8GVkTFTDx2wHHZzJXeVqc6LmcjjcMJqWQqpiF::v0',
2022-05-11T13:40:00.003044428Z   account: '0x90077FA7618108781FF30Ede85141ca3F53F4517'
2022-05-11T13:40:00.003046788Z }
2022-05-11T13:40:00.003512915Z Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
2022-05-11T13:40:00.003570975Z     at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
2022-05-11T13:40:00.003581805Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:419:49
2022-05-11T13:40:00.003607895Z     at runMicrotasks (<anonymous>)
2022-05-11T13:40:00.003616625Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2022-05-11T13:40:00.003639025Z   receipt: undefined
2022-05-11T13:40:00.003646805Z }
2022-05-11T13:40:00.003665735Z ------------------------------------------------------
2022-05-11T13:40:00.003793714Z response createAnchor 428. Error :  Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
2022-05-11T13:40:00.003813914Z     at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
2022-05-11T13:40:00.003843203Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:419:49
2022-05-11T13:40:00.003851813Z     at runMicrotasks (<anonymous>)
2022-05-11T13:40:00.003873313Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2022-05-11T13:40:00.003881743Z   receipt: undefined
2022-05-11T13:40:00.003899873Z }
2022-05-11T13:40:00.005967640Z {
2022-05-11T13:40:00.006005950Z   anchorID: '29fgyfS13tr4gjabfTYGXNFDRPzLXquER412vXvsUzZ3EygdGJMpcDiSGJPirWZsp2ASPcdrxVumS4UnsXiBZjbf64Ry28P',
2022-05-11T13:40:00.006017900Z   anchorValue: 'G73iPJYaFmfMiBcFYy1vLzEqPxiV3jhT6ybQbGNyRCBzh8HuhnnRuY2UXoZze6hy9Vn8Z2oYLXs3G5E1ccB7LBUYpJvv3'
2022-05-11T13:40:00.006023070Z }
2022-05-11T13:40:00.006025770Z ------------------------------------------------------
...
```

```txt
...
2022-05-11T13:11:29.006609994Z WARN [05-11|13:11:29.006] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state="Accept request" seq=667624 err="old message"                      number=667623 hash="276cd6…a8ad62"
2022-05-11T13:13:43.674140761Z WARN [05-11|13:13:43.674] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=667753 err="future message"                   number=667754 hash="c6bc24…8a9c85"
2022-05-11T13:22:19.016793441Z WARN [05-11|13:22:19.016] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state="Accept request" seq=668263 err="old message"                      number=668262 hash="fe2c07…659d8a"
2022-05-11T13:27:49.007250592Z WARN [05-11|13:27:49.007] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state="Accept request" seq=668592 err="old message"                      number=668591 hash="974412…f78e21"
2022-05-11T13:29:25.371782790Z WARN [05-11|13:29:25.370] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=668684 err="future message"                   number=668685 hash="9fe04f…6afb54"
2022-05-11T13:32:09.007648320Z WARN [05-11|13:32:09.007] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state="Accept request" seq=668848 err="old message"                      number=668847 hash="f704d8…c7e6ac"
2022-05-11T13:38:58.016306834Z WARN [05-11|13:38:58.013] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state="Accept request" seq=669256 err="old message"                      number=669255 hash="be7964…ea5cf0"
2022-05-11T13:41:31.289734386Z WARN [05-11|13:41:31.283] unexpected request                       address=0xf9c6b3f6Ae492dcb802C7C4a90e95F1E3c75a602 state=Committed        seq=669404 err="future message"                   number=669405 hash="10e377…1803d0"
...
```

**Comment by joaoluis-pdm** [comment]
Attempt to restart the quorum nodes.

```sh
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/quorum$ docker-compose stop
Stopping node4-qbn ... done
Stopping node1-qbn ... 
Stopping node2-qbn ... done
Stopping node3-qbn ... done

ERROR: for node1-qbn  UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=70)
ERROR: An HTTP request took too long to complete. Retry with --verbose to obtain debug information.
If you encounter this issue regularly because of slow network conditions, consider setting COMPOSE_HTTP_TIMEOUT to a higher value (current value: 60).

```

**Comment by joaoluis-pdm** [comment]
Errors still happen on ethAdapter.
```txt
2022-05-11T13:40:00.003003049Z {
2022-05-11T13:40:00.003038148Z   anchorID: 'ssi:cza:traceability:831i3LKa82i8kQgaxfb5hR47WpujVGCu8owyyBjZ1Bj7::v0',
2022-05-11T13:40:00.003041848Z   newAnchorValue: 'ssi:hl:traceability:7PMBFGe8GVkTFTDx2wHHZzJXeVqc6LmcjjcMJqWQqpiF::v0',
2022-05-11T13:40:00.003044428Z   account: '0x90077FA7618108781FF30Ede85141ca3F53F4517'
2022-05-11T13:40:00.003046788Z }
2022-05-11T13:40:00.003512915Z Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
2022-05-11T13:40:00.003570975Z     at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
2022-05-11T13:40:00.003581805Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:419:49
2022-05-11T13:40:00.003607895Z     at runMicrotasks (<anonymous>)
2022-05-11T13:40:00.003616625Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2022-05-11T13:40:00.003639025Z   receipt: undefined
2022-05-11T13:40:00.003646805Z }
2022-05-11T13:40:00.003665735Z ------------------------------------------------------
2022-05-11T13:40:00.003793714Z response createAnchor 428. Error :  Error: Transaction was not mined within 750 seconds, please make sure your transaction was properly sent. Be aware that it might still be mined!
2022-05-11T13:40:00.003813914Z     at Object.TransactionError (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-helpers/lib/errors.js:87:21)
2022-05-11T13:40:00.003843203Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:419:49
2022-05-11T13:40:00.003851813Z     at runMicrotasks (<anonymous>)
2022-05-11T13:40:00.003873313Z     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
2022-05-11T13:40:00.003881743Z   receipt: undefined
2022-05-11T13:40:00.003899873Z }
2022-05-11T13:40:00.005967640Z {
2022-05-11T13:40:00.006005950Z   anchorID: '29fgyfS13tr4gjabfTYGXNFDRPzLXquER412vXvsUzZ3EygdGJMpcDiSGJPirWZsp2ASPcdrxVumS4UnsXiBZjbf64Ry28P',
2022-05-11T13:40:00.006017900Z   anchorValue: 'G73iPJYaFmfMiBcFYy1vLzEqPxiV3jhT6ybQbGNyRCBzh8HuhnnRuY2UXoZze6hy9Vn8Z2oYLXs3G5E1ccB7LBUYpJvv3'
2022-05-11T13:40:00.006023070Z }
2022-05-11T13:40:00.006025770Z ------------------------------------------------------
2022-05-11T14:28:07.294658498Z ssi:cza:traceability:6nddJm3hkXDS7WcBjybswgDJfq7qfjDGGRpsqvs6sNKT::v0
2022-05-11T14:28:10.206095731Z Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-05-11T14:28:10.206131371Z     at ABICoder.decodeParametersWith (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-05-11T14:28:10.206150431Z     at ABICoder.decodeParameters (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-05-11T14:28:10.206153401Z     at Contract._decodeMethodReturn (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:493:22)
2022-05-11T14:28:10.206155751Z     at Method.outputFormatter (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:800:42)
2022-05-11T14:28:10.206157941Z     at Method.formatOutput (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:148:54)
2022-05-11T14:28:10.206160181Z     at sendTxCallback (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:531:33)
2022-05-11T14:28:10.206162301Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-requestmanager/lib/index.js:305:9
2022-05-11T14:28:10.206164401Z     at XMLHttpRequest.request.onreadystatechange (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-providers-http/lib/index.js:98:13)
2022-05-11T14:28:10.206166681Z     at XMLHttpRequestEventTarget.dispatchEvent (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2022-05-11T14:28:10.206168951Z     at XMLHttpRequest._setReadyState (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2022-05-11T14:28:10.206171091Z     at XMLHttpRequest._onHttpResponseEnd (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2022-05-11T14:28:10.206173231Z     at IncomingMessage.<anonymous> (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2022-05-11T14:28:10.206175791Z     at IncomingMessage.emit (events.js:326:22)
2022-05-11T14:28:10.206177861Z     at endReadableNT (_stream_readable.js:1241:12)
2022-05-11T14:28:10.206180451Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-05-11T14:28:10.206182811Z response getLastVersion 500 29fgyfS13tr4gjabfTYGXNFDRPzLXqqU9k1Rct6tc84RmTy1k7etmWdHqDAh9sQgw1EHvAkVGWTgi3oXkz3GkgbPBbPF6UF
2022-05-11T14:28:51.826762870Z ssi:cza:traceability:6nddJm3hkXDS7WcBjybswgDJfq7qfjDGGRpsqvs6sNKT::v0
2022-05-11T14:28:51.829466891Z Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-05-11T14:28:51.829483011Z     at ABICoder.decodeParametersWith (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-05-11T14:28:51.829487491Z     at ABICoder.decodeParameters (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-05-11T14:28:51.829490781Z     at Contract._decodeMethodReturn (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:493:22)
2022-05-11T14:28:51.829493881Z     at Method.outputFormatter (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:800:42)
2022-05-11T14:28:51.829519510Z     at Method.formatOutput (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:148:54)
2022-05-11T14:28:51.829524820Z     at sendTxCallback (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:531:33)
2022-05-11T14:28:51.829529680Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-requestmanager/lib/index.js:305:9
2022-05-11T14:28:51.829534540Z     at XMLHttpRequest.request.onreadystatechange (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-providers-http/lib/index.js:98:13)
2022-05-11T14:28:51.829539570Z     at XMLHttpRequestEventTarget.dispatchEvent (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2022-05-11T14:28:51.829544530Z     at XMLHttpRequest._setReadyState (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2022-05-11T14:28:51.829549320Z     at XMLHttpRequest._onHttpResponseEnd (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2022-05-11T14:28:51.829554180Z     at IncomingMessage.<anonymous> (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2022-05-11T14:28:51.829559690Z     at IncomingMessage.emit (events.js:326:22)
2022-05-11T14:28:51.829564290Z     at endReadableNT (_stream_readable.js:1241:12)
2022-05-11T14:28:51.829569860Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-05-11T14:28:51.829574550Z response getLastVersion 500 29fgyfS13tr4gjabfTYGXNFDRPzLXqqU9k1Rct6tc84RmTy1k7etmWdHqDAh9sQgw1EHvAkVGWTgi3oXkz3GkgbPBbPF6UF
```

**Comment by joaoluis-pdm** [comment]
Trying harder to restart the quorum nodes
```sh
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/quorum$ docker-compose down
Stopping node4-qbn ... done
Stopping node1-qbn ... done
Stopping node2-qbn ... done
Stopping node3-qbn ... done
Removing node4-qbn ... done
Removing node1-qbn ... done
Removing node2-qbn ... done
Removing node3-qbn ... done
Removing network qbn-net
ERROR: error while removing network: network qbn-net id a9e6b17643f9aa6c30f6094e4021a2f5144a1c52f0fbfbef1ffef1bf80b726d1 has active endpoints
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/quorum$ cd ../ethadapter/EthAdapter/
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/ethadapter/EthAdapter$ docker-compose down
Stopping ethAdapter ... done
Removing ethAdapter ... done
Network qbn-net is external, skipping
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/ethadapter/EthAdapter$ cd ..
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/ethadapter$ cd ..
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace$ cd quorum/
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/quorum$ docker-compose up -d
Creating node3-qbn ... done
Creating node1-qbn ... done
Creating node2-qbn ... done
Creating node4-qbn ... done
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/quorum$ cd ../ethadapter/EthAdapter/
pharmaledger@fgt-dev-pl:~/blockchain-node-workspace/ethadapter/EthAdapter$ docker-compose up -d
Creating ethAdapter ... done
```

**Comment by joaoluis-pdm** [comment]
Reading from the blockchain also failed.

```txt
2022-05-11T14:49:02.447019608Z ssi:cza:traceability:6nddJm3hkXDS7WcBjybswgDJfq7qfjDGGRpsqvs6sNKT::v0
2022-05-11T14:49:02.595007198Z ssi:cza:traceability:FVBreVkKTTYj4m2PWY8hJ5tWjeSykQantRstHYEguLz1::v0
2022-05-11T14:49:03.231706294Z Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-05-11T14:49:03.231739754Z     at ABICoder.decodeParametersWith (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-05-11T14:49:03.231743354Z     at ABICoder.decodeParameters (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-05-11T14:49:03.231745924Z     at Contract._decodeMethodReturn (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:493:22)
2022-05-11T14:49:03.231748374Z     at Method.outputFormatter (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:800:42)
2022-05-11T14:49:03.231750864Z     at Method.formatOutput (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:148:54)
2022-05-11T14:49:03.231754293Z     at sendTxCallback (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:531:33)
2022-05-11T14:49:03.231757503Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-requestmanager/lib/index.js:305:9
2022-05-11T14:49:03.231770643Z     at XMLHttpRequest.request.onreadystatechange (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-providers-http/lib/index.js:98:13)
2022-05-11T14:49:03.231783563Z     at XMLHttpRequestEventTarget.dispatchEvent (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2022-05-11T14:49:03.231786073Z     at XMLHttpRequest._setReadyState (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2022-05-11T14:49:03.231788363Z     at XMLHttpRequest._onHttpResponseEnd (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2022-05-11T14:49:03.231790583Z     at IncomingMessage.<anonymous> (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2022-05-11T14:49:03.231793333Z     at IncomingMessage.emit (events.js:326:22)
2022-05-11T14:49:03.231795683Z     at endReadableNT (_stream_readable.js:1241:12)
2022-05-11T14:49:03.231800563Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-05-11T14:49:03.231802833Z response getLastVersion 500 29fgyfS13tr4gjabfTYGXNFDRPzLXrRJv9USDXTGyFMdocKqqakZePhuBkYjmhipNhkZUcVCv8M3b1VBu4xNgkjSbrDdZy1
2022-05-11T14:49:03.721622667Z Error: Returned values aren't valid, did it run Out of Gas? You might also see this error if you are not using the correct ABI for the contract you are retrieving data from, requesting data from a block number that does not exist, or querying a node which is not fully synced.
2022-05-11T14:49:03.721640967Z     at ABICoder.decodeParametersWith (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:297:15)
2022-05-11T14:49:03.721644207Z     at ABICoder.decodeParameters (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-abi/lib/index.js:284:17)
2022-05-11T14:49:03.721646577Z     at Contract._decodeMethodReturn (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:493:22)
2022-05-11T14:49:03.721648757Z     at Method.outputFormatter (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-eth-contract/lib/index.js:800:42)
2022-05-11T14:49:03.721651027Z     at Method.formatOutput (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:148:54)
2022-05-11T14:49:03.721653287Z     at sendTxCallback (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-method/lib/index.js:531:33)
2022-05-11T14:49:03.721655387Z     at /blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-core-requestmanager/lib/index.js:305:9
2022-05-11T14:49:03.721657507Z     at XMLHttpRequest.request.onreadystatechange (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/web3-providers-http/lib/index.js:98:13)
2022-05-11T14:49:03.721659757Z     at XMLHttpRequestEventTarget.dispatchEvent (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:22)
2022-05-11T14:49:03.721662317Z     at XMLHttpRequest._setReadyState (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:208:14)
2022-05-11T14:49:03.721676287Z     at XMLHttpRequest._onHttpResponseEnd (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:318:14)
2022-05-11T14:49:03.721678967Z     at IncomingMessage.<anonymous> (/blockchain-node-workspace/ethadapter/EthAdapter/node_modules/xhr2-cookies/dist/xml-http-request.js:289:61)
2022-05-11T14:49:03.721681557Z     at IncomingMessage.emit (events.js:326:22)
2022-05-11T14:49:03.721683577Z     at endReadableNT (_stream_readable.js:1241:12)
2022-05-11T14:49:03.721685947Z     at processTicksAndRejections (internal/process/task_queues.js:84:21)
2022-05-11T14:49:03.721688057Z response getLastVersion 500 29fgyfS13tr4gjabfTYGXNFDRPzLXqqU9k1Rct6tc84RmTy1k7etmWdHqDAh9sQgw1EHvAkVGWTgi3oXkz3GkgbPBbPF6UF
```

**Comment by joaoluis-pdm** [comment]
Closed as wontfix for now.
