### ISSUE TITLE
Error: Only one manager allowed appeared when testing hlf-adapter / Shipping a recalled batch

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#79]
During the tests with hlf-adapter https://github.com/PharmaLedger-IMI/blockchain-hf-workspace the following error appeared:
```txt
2022-05-16T09:42:34.375804268Z (1) chunk= {"status":"confirmed","extraInfo":"Confirmed into stock by a test script!"}
2022-05-16T09:42:34.375811588Z 
2022-05-16T09:42:34.375816548Z (end) data= {"status":"confirmed","extraInfo":"Confirmed into stock by a test script!"} 
2022-05-16T09:42:34.375821998Z 
2022-05-16T09:42:34.418616005Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkEGdTKox8RCMH5XXc44xZAPiGoRGhdiBAKxXpepwXwPNW9VGUk2b6abGyZ1vYo6DnCo with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:34.444376340Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkFpCdqkFuB197SRUanKhwEwddYfjtigcZ7K3QemLk96Qbs9jaVWFjXzFsLMrzwUZwnw with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.617956926Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkEGdTKox8RCMH5XXc44xZAPiGoRGhdiBAKxXpepwXwPNW9VGUk2b6abGyZ1vYo6DnCo with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.638679099Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkFpCdqkFuB197SRUanKhwEwddYfjtigcZ7K3QemLk96Qbs9jaVWFjXzFsLMrzwUZwnw with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.650635662Z update Record tableName=simpleShipments key MAH136366355-16526936566004792710 record {
2022-05-16T09:42:36.650670271Z   key: 'MAH136366355-16526936566004792710',
2022-05-16T09:42:36.650675831Z   value: '65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR',
2022-05-16T09:42:36.650680551Z   shipmentId: 'MAH136366355-16526936566004792710',
2022-05-16T09:42:36.650684791Z   requesterId: 'WHS000001',
2022-05-16T09:42:36.650688901Z   orderId: 'WHS000001-2022-05-16T09:34:16.546Z',
2022-05-16T09:42:36.650693101Z   senderId: 'MAH136366355'
2022-05-16T09:42:36.650697171Z }
2022-05-16T09:42:36.655033017Z Committing batch in simpleShipments
2022-05-16T09:42:38.813240492Z New BATCH_SSI in domain traceability
2022-05-16T09:42:38.830975372Z Sending message Message {
2022-05-16T09:42:38.830987691Z   api: 'simpleShipments',
2022-05-16T09:42:38.830989851Z   message: '65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR'
2022-05-16T09:42:38.830992031Z } to did did:ssi:name:traceability:MAH136366355
2022-05-16T09:42:38.848708251Z Message sent to MAH136366355, receivedShipments, 65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR
2022-05-16T09:42:38.848819600Z New PRODUCT_SSI in domain traceability
2022-05-16T09:42:38.867283016Z New PRODUCT_SSI in domain traceability
2022-05-16T09:42:38.872009009Z update Record tableName=stock key 00366582505358 record Stock {
2022022-05-16T09:42:34.375804268Z (1) chunk= {"status":"confirmed","extraInfo":"Confirmed into stock by a test script!"}
2022-05-16T09:42:34.375811588Z 
2022-05-16T09:42:34.375816548Z (end) data= {"status":"confirmed","extraInfo":"Confirmed into stock by a test script!"} 
2022-05-16T09:42:34.375821998Z 
2022-05-16T09:42:34.418616005Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkEGdTKox8RCMH5XXc44xZAPiGoRGhdiBAKxXpepwXwPNW9VGUk2b6abGyZ1vYo6DnCo with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:34.444376340Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkFpCdqkFuB197SRUanKhwEwddYfjtigcZ7K3QemLk96Qbs9jaVWFjXzFsLMrzwUZwnw with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.617956926Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkEGdTKox8RCMH5XXc44xZAPiGoRGhdiBAKxXpepwXwPNW9VGUk2b6abGyZ1vYo6DnCo with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.638679099Z Loading status for ShipmentLine SSI 65FmT6jYpmQXh9ETs68RdMxy7LL7pkFpCdqkFuB197SRUanKhwEwddYfjtigcZ7K3QemLk96Qbs9jaVWFjXzFsLMrzwUZwnw with status SSI o7oyuxBsug4VozamZzwhz8S
UPhQfUAujtPbuYbkNAREXDYmg2hyuWXLqDJcMdLvQLD2NFoVMTpTdDi138nqYoZJzDonJn5SmnqjHXzdNXXaooRxUZyFRdYj2UxsdvQew2h3njEMA2DjkWhLKUoHfLiuvko9eXzQEdUzGtygnH67pUgwFsmpaKz97JKYM65JEM1MG2jaQBov81VRihdojaajdh
2022-05-16T09:42:36.650635662Z update Record tableName=simpleShipments key MAH136366355-16526936566004792710 record {
2022-05-16T09:42:36.650670271Z   key: 'MAH136366355-16526936566004792710',
2022-05-16T09:42:36.650675831Z   value: '65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR',
2022-05-16T09:42:36.650680551Z   shipmentId: 'MAH136366355-16526936566004792710',
2022-05-16T09:42:36.650684791Z   requesterId: 'WHS000001',
2022-05-16T09:42:36.650688901Z   orderId: 'WHS000001-2022-05-16T09:34:16.546Z',
2022-05-16T09:42:36.650693101Z   senderId: 'MAH136366355'
2022-05-16T09:42:36.650697171Z }
2022-05-16T09:42:36.655033017Z Committing batch in simpleShipments
2022-05-16T09:42:38.813240492Z New BATCH_SSI in domain traceability
2022-05-16T09:42:38.830975372Z Sending message Message {
2022-05-16T09:42:38.830987691Z   api: 'simpleShipments',
2022-05-16T09:42:38.830989851Z   message: '65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR'
2022-05-16T09:42:38.830992031Z } to did did:ssi:name:traceability:MAH136366355
2022-05-16T09:42:38.848708251Z Message sent to MAH136366355, receivedShipments, 65FmT6jYpmQXh9ETs68RdMxy7LL7pkF3e41EmjhmvkmRWqdL1Hz6oTtgoZvsvPNXATTNotZW8fXjGpRXkJj8Z4BsecHySTuR
2022-05-16T09:42:38.848819600Z New PRODUCT_SSI in domain traceability
2022-05-16T09:42:38.867283016Z New PRODUCT_SSI in domain traceability
2022-05-16T09:42:38.872009009Z update Record tableName=stock key 00366582505358 record Stock {
2022-05-16T09:42:38.872039839Z   name: 'Bridion',
2022-05-16T09:42:38.872042159Z   gtin: '00366582505358',
2022-05-16T09:42:38.872044049Z   description: 'Injectable Solution 100mg/ml x 10 2ml vials',
2022-05-16T09:42:38.872046039Z   manufName: 'MAH136366355',
2022-05-16T09:42:38.872047949Z   batches: [
2022-05-16T09:42:38.872049739Z     Batch {
2022-05-16T09:42:38.872051509Z       batchNumber: 'R034995',
2022-05-16T09:42:38.872053339Z       expiry: 2028-08-30T23:00:00.000Z,
2022-05-16T09:42:38.872055179Z       serialNumbers: [],
2022-05-16T09:42:38.872056949Z       quantity: 150,
2022-05-16T09:42:38.872058729Z       batchStatus: [Status]
2022-05-16T09:42:38.872060519Z     }
2022-05-16T09:42:38.872062279Z   ],
2022-05-16T09:42:38.872064049Z   status: 'available',
2022-05-16T09:42:38.872065949Z   quantity: 150
2022-05-16T09:42:38.872067739Z }
2022-05-16T09:42:38.877089581Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:38.877167740Z Stock for Product 00366582505358 updated
2022-05-16T09:42:38.877218820Z Updated Stock for 00366582505358 batch R034995. 
2022-05-16T09:42:38.877326229Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:38.888559096Z [FGT-API - 1652694158888] - All MAHs resolved
2022-05-16T09:42:38.889740499Z Lines Notice sent to Manufacturers
2022-05-16T09:42:38.893459338Z New BATCH_SSI in domain traceability
2022-05-16T09:42:39.042310636Z update Record tableName=stock key 00191778005295 record Stock {2-05-16T09:42:38.872039839Z   name: 'Bridion',
2022-05-16T09:42:38.872042159Z   gtin: '00366582505358',
2022-05-16T09:42:38.872044049Z   description: 'Injectable Solution 100mg/ml x 10 2ml vials',
2022-05-16T09:42:38.872046039Z   manufName: 'MAH136366355',
2022-05-16T09:42:38.872047949Z   batches: [
2022-05-16T09:42:38.872049739Z     Batch {
2022-05-16T09:42:38.872051509Z       batchNumber: 'R034995',
2022-05-16T09:42:38.872053339Z       expiry: 2028-08-30T23:00:00.000Z,
2022-05-16T09:42:38.872055179Z       serialNumbers: [],
2022-05-16T09:42:38.872056949Z       quantity: 150,
2022-05-16T09:42:38.872058729Z       batchStatus: [Status]
2022-05-16T09:42:38.872060519Z     }
2022-05-16T09:42:38.872062279Z   ],
2022-05-16T09:42:38.872064049Z   status: 'available',
2022-05-16T09:42:38.872065949Z   quantity: 150
2022-05-16T09:42:38.872067739Z }
2022-05-16T09:42:38.877089581Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:38.877167740Z Stock for Product 00366582505358 updated
2022-05-16T09:42:38.877218820Z Updated Stock for 00366582505358 batch R034995. 
2022-05-16T09:42:38.877326229Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:38.888559096Z [FGT-API - 1652694158888] - All MAHs resolved
2022-05-16T09:42:38.889740499Z Lines Notice sent to Manufacturers
2022-05-16T09:42:38.893459338Z New BATCH_SSI in domain traceability
2022-05-16T09:42:39.042310636Z update Record tableName=stock key 00191778005295 record Stock {
2022-05-16T09:42:39.042322146Z   name: 'Gardasil 9',
2022-05-16T09:42:39.042324196Z   gtin: '00191778005295',
2022-05-16T09:42:39.042326116Z   description: 'Injectable suspension, pre-filled syringe, 0,5ml',
2022-05-16T09:42:39.042327986Z   manufName: 'MAH136366355',
2022-05-16T09:42:39.042329786Z   batches: [
2022-05-16T09:42:39.042331636Z     Batch {
2022-05-16T09:42:39.042333396Z       batchNumber: 'U002114',
2022-05-16T09:42:39.042335216Z       expiry: 2023-08-30T23:00:00.000Z,
2022-05-16T09:42:39.042337106Z       serialNumbers: [],
2022-05-16T09:42:39.042338886Z       quantity: 150,
2022-05-16T09:42:39.042340656Z       batchStatus: [Status]
2022-05-16T09:42:39.042342466Z     }
2022-05-16T09:42:39.042344216Z   ],
2022-05-16T09:42:39.042345986Z   status: 'available',
2022-05-16T09:42:39.042347786Z   quantity: 150
2022-05-16T09:42:39.042349556Z }
2022-05-16T09:42:39.044720302Z Sending message Message {
2022-05-16T09:42:39.044728702Z   api: 'shipmentLines',
2022-05-16T09:42:39.044730762Z   message: '["65FmT6jYpmQXh9ETs68RdMxy7LL7pkEGdTKox8RCMH5XXc44xZAPiGoRGhdiBAKxXpepwXwPNW9VGUk2b6abGyZ1vYo6DnCo","65FmT6jYpmQXh9ETs68RdMxy7LL7pkFpCdqkFuB197SRUanKhwEwddYfjtigcZ7K3QemLk96Qbs9jaVWFjXzFsLMrzwUZwnw"]'
2022-05-16T09:42:39.044733202Z } to did did:ssi:name:traceability:MAH136366355
2022-05-16T09:42:39.049221557Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:39.049231027Z Stock for Product 00191778005295 updated
2022-05-16T09:42:39.049253837Z Updated Stock for 00191778005295 batch U002114. 
2022-05-16T09:42:39.049271947Z Other Batch operations in progress in table simpleShipments. not committing just yet
2022-05-16T09:42:39.050670609Z (node:1306) UnhandledPromiseRejectionWarning: Error: Only one manager allowed
2022-05-16T09:42:39.050678309Z     at DBLock.allow (/fgt-workspace/pdm-dsu-toolkit/managers/DBLock.js:50:19)
2022-05-16T09:42:39.050680419Z     at SimpleShipmentManager.batchAllow (/fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:164:21)
2022-05-16T09:42:39.050682399Z     at /fgt-workspace/fgt-api/managers/SimpleShipmentManager.js:348:38
2022-05-16T09:42:39.050684369Z     at /fgt-workspace/fgt-dsu-wizard/managers/StockManager.js:254:21
2022-05-16T09:42:39.050686259Z     at DBLock.commitBatch (/fgt-workspace/pdm-dsu-toolkit/managers/DBLock.js:143:9)
2022-05-16T09:42:39.050688169Z     at StockManager.commitBatch (/fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:156:21)
2022-05-16T09:42:39.050696739Z     at /fgt-workspace/fgt-dsu-wizard/managers/StockManager.js:238:22
2022-05-16T09:42:39.050698829Z     at /fgt-workspace/pdm-dsu-toolkit/services/utils.js:247:5
2022-05-16T09:42:39.050700779Z     at iterator (/fgt-workspace/pdm-dsu-toolkit/services/utils.js:231:11)
2022-05-16T09:42:39.050702679Z     at /fgt-workspace/pdm-dsu-toolkit/services/utils.js:238:23
2022-05-16T09:42:39.050704549Z     at /fgt-workspace/fgt-dsu-wizard/managers/StockManager.js:214:25
2022-05-16T09:42:39.050706429Z     at /fgt-workspace/fgt-dsu-wizard/managers/StockManager.js:189:21
2022-05-16T09:42:39.050708289Z     at /fgt-workspace/fgt-dsu-wizard/managers/StockManager.js:97:13
2022-05-16T09:42:39.050710169Z     at /fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:923:17
2022-05-16T09:42:39.050712049Z     at DBLock.commitBatch (/fgt-workspace/pdm-dsu-toolkit/managers/DBLock.js:143:9)
2022-05-16T09:42:39.050713959Z     at StockManager.commitBatch (/fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:156:21)
2022-05-16T09:42:39.050715869Z     at /fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:918:18
2022-05-16T09:42:39.050717749Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:17589:17
2022-05-16T09:42:39.050719619Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:18803:25
2022-05-16T09:42:39.050721489Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:18640:24
2022-05-16T09:42:39.050723349Z     at callCallback (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:38274:9)
2022-05-16T09:42:39.050725249Z     at Object.decrement (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:38257:20)
2022-05-16T09:42:39.050727159Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:18651:37
2022-05-16T09:42:39.050729039Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:18619:13
2022-05-16T09:42:39.050730899Z     at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:40192:20)
2022-05-16T09:42:39.050732789Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:3867:24
2022-05-16T09:42:39.050735059Z     at LatestVersionStrategy.decisionFunction (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:1869:20)
...
```
(github upload is giving HTTP 422)
Full logs on http://homes.pdmfc.com/jpsl/PharmaLedger/fgtDevAllLogs20220516.zip

**Comment by joaoluis-pdm** [comment]
The issue may be related to shipping a recalled batch.

**Comment by joaoluis-pdm** [comment]
Question for @TiagoV-PDMFC 

should line https://github.com/PharmaLedger-IMI/fgt-workspace//blob/e4701e38a67adb26120a3893b3e9cb8e5bcc182d/fgt-api/managers/SimpleShipmentManager.js#L351

be replaced by 
```js
                                    if (!err) {
                                        self.batchDisallow(self.directoryManager);
                                        return cb();
                                    }
```

?

**Comment by joaoluis-pdm** [comment]
With the fix above, repeating the test
```sh
fgt-workspace/bin/environment$ node --unhandled-rejections=strict wsCreateStuff.js --sleep=70000 2>&1 | tee -a wsCreateStuffLocal9b.log
```
twice, now fails with:
```txt
...
http POST {"path":"/traceability/sale/create","method":"POST","headers":{"content-type":"application/json","content-length":141,"Authorization":"Basic UEhBMDAwMDAxOlRoaXMxc1N1Y2hBUzNjdXJlUGFzc3cwcmQ="},"hostname":"api-pha1.localhost","port":"8080"} {"id":"PHA000001-2022-06-06T20:30:55.606Z","productList":[{"gtin":"00366582505358","batchNumber":"R034995","serialNumber":"25838881233366"}]}
res 619ms {
  status: 400,
  error: 'Bad Request',
  message: 'Product gtin 00366582505358, batch R034995: is not available for sale, because batchStatus is recall. '
}
/export/home/jpsl/develop/PharmaLedger/fgt-workspace/bin/environment/wsCreateStuff.js:741
            throw new Error("sale/create "+batch.batchNumber+" at "+sellerActor.id.secret+" reply has no productList: "+JSON.stringify(resSale));
                  ^

Error: sale/create R034995 at PHA000001 reply has no productList: {"status":400,"error":"Bad Request","message":"Product gtin 00366582505358, batch R034995: is not available for sale, because batchStatus is recall. "}
```
This might be the correct behaviour.

Ask @TiagoV-PDMFC if the traceability system should prevent sales ? (Shouldn't the traceability be neutral ? If some dispensed the product, the traceability system should simply record that fact).

For now adding to the release notes, and closing the issue.
