### ISSUE TITLE
/shipment/create and /shipment/update/{shipmentId} out-of-order processing

### ISSUE THREAD

**Issue by joaoluis-pdm** [PharmaLedger-IMI/fgt-workspace#91]
When a sender performs /shipment/create and then /shipment/update/{shipmentId} without waiting for the receiver to process the messages, it is likely that the receiver will reject the  /shipment/update/{shipmentId} message with an error 

```txt
2022-07-18T13:47:01.780234698Z Error processing Api simpleShipments Error
2022-07-18T13:47:01.780246268Z     at ErrorWrapper (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:22686:22)
2022-07-18T13:47:01.780248658Z     at createOpenDSUErrorWrapper (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:22713:12)
2022-07-18T13:47:01.780250728Z     at SimpleShipmentManager._err (/fgt-workspace/pdm-dsu-toolkit/services/utils.js:185:39)
2022-07-18T13:47:01.780252788Z     at /fgt-workspace/pdm-dsu-toolkit/managers/Manager.js:341:29
2022-07-18T13:47:01.780254708Z     at /fgt-workspace/fgt-api/managers/SimpleShipmentManager.js:467:118
2022-07-18T13:47:01.780256618Z     at /fgt-workspace/fgt-api/managers/SimpleShipmentManager.js:447:32
2022-07-18T13:47:01.780258518Z     at /fgt-workspace/fgt-api/services/SimpleShipmentService.js:244:24
2022-07-18T13:47:01.780260428Z     at /fgt-workspace/fgt-api/services/SimpleShipmentService.js:98:33
2022-07-18T13:47:01.780262318Z     at populateShipmentLineStatus (/fgt-workspace/fgt-api/services/SimpleShipmentService.js:85:44)
2022-07-18T13:47:01.780264298Z     at /fgt-workspace/fgt-api/services/SimpleShipmentService.js:90:37
2022-07-18T13:47:01.780267138Z     at /fgt-workspace/fgt-dsu-wizard/services/ShipmentLineService.js:48:25
2022-07-18T13:47:01.780270028Z     at returnFunc (/fgt-workspace/fgt-dsu-wizard/services/StatusService.js:76:32)
2022-07-18T13:47:01.780273048Z     at /fgt-workspace/fgt-dsu-wizard/services/StatusService.js:81:36
2022-07-18T13:47:01.780275898Z     at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:40192:20)
2022-07-18T13:47:01.780278778Z     at _readFile (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:688:49)
2022-07-18T13:47:01.780291648Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1221:17
2022-07-18T13:47:01.780294887Z     at waitIfDSUIsRefreshing (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:446:20)
2022-07-18T13:47:01.780297807Z     at Archive.readFile (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:1210:9)
2022-07-18T13:47:01.780300787Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1229:36
2022-07-18T13:47:01.780303757Z     at newFn (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:40192:20)
2022-07-18T13:47:01.780305877Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:1836:32
...
2022-07-18T13:47:01.780424757Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:597:24
2022-07-18T13:47:01.780426657Z     at /fgt-workspace/privatesky/psknode/bundles/openDSU.js:15095:13
2022-07-18T13:47:01.780428537Z     at executeForSingleEntry (/fgt-workspace/privatesky/psknode/bundles/openDSU.js:27578:13)
2022-07-18T13:47:01.780430487Z     at runMicrotasks (<anonymous>)
2022-07-18T13:47:01.780432607Z     at processTicksAndRejections (node:internal/process/task_queues:96:5) {
2022-07-18T13:47:01.780434527Z   originalMessage: '',
2022-07-18T13:47:01.780436347Z   previousError: [ 'Status update from created to delivered is not allowed' ],
2022-07-18T13:47:01.780438347Z   debug_message: 'Record processing failed: {"api":"simpleShipments","message":"65FmT6jYpmQXh9ETs68RdMxy7LL7pkFSWcb34VbnnrPVUyXTXpJWmWmveXFJmhJzSKNTY8H4Ny5g7N6t94Wdq92JQ1zZwyD9","key":"1658152020463"}'
2022-07-18T13:47:01.780441147Z }
2022-07-18T13:47:01.780487556Z Message received [object Object]
2022-07-18T13:47:01.780542936Z _startMessageListener did:ssi:name:traceability:WHS000001
```

... and then, the referred shipment is "stuck" without being possible to change its status (the status is already changed on the sender, but the receiver will refuse further statuses updates).

Tip to reproduce: Use the https://github.com/PharmaLedger-IMI/fgt-workspace/blob/master/bin/environment/wsCreateStuff.js to create and update shipments with a very low --sleep delay.

**Comment by joaoluis-pdm** [comment]
Commit https://github.com/PharmaLedger-IMI/fgt-workspace/commit/ca5eee438c99beb9051ac6f5b2b967e76c287bc4
upgraded to psk-release 2022-07-19 build 611 b5ba7d8444581b2ce46d69dab7caeb797b79ed60 was intended to fix MQ delivering order, but had no impact.

The problem remains the same.

**Comment by joaoluis-pdm** [comment]
More tips on how to re-produce using bin/environment/wsCreateStuff.js:

1 - (optional) edit your local copy of bin/environment/wsCreateStuff.js and set to use just a single MAH. It must be the same MAH that creates shipments. (Cut out the time of creating products and batches).
```js
diff --git a/bin/environment/wsCreateStuff.js b/bin/environment/wsCreateStuff.js
index b5bc6897..53a50771 100644
--- a/bin/environment/wsCreateStuff.js
+++ b/bin/environment/wsCreateStuff.js
@@ -32,7 +32,7 @@ const ShipmentStatus = require('../../fgt-dsu-wizard/model/ShipmentStatus');
 const BatchStatus = require('../../fgt-dsu-wizard/model/BatchStatus');
 
 const credentials = require('./credentials/credentialsTests'); // TODO require ../../docker/api/env/mah-*.json ?
-const MAHS = [credentials.PFIZER, credentials.MSD, credentials.ROCHE, credentials.BAYER, credentials.NOVO_NORDISK, credentials.GSK, credentials.TAKEDA, credentials.SANOFI];
+const MAHS = [credentials.MSD];
```

2 - create products and batches for that MAH
```sh
cd bin/environment
node --unhandled-rejections=strict wsCreateStuff.js --env=local --products=test --batches=test --shipments=none --sales=none --receipts=none --traceability=none
```

**Comment by joaoluis-pdm** [comment]
[shipCreateUpdate.zip](https://github.com/PharmaLedger-IMI/fgt-workspace/files/9149537/shipCreateUpdate.zip)

**Comment by joaoluis-pdm** [comment]
Internal informal discussion (in pt) about the fix proposal:
```txt
[ontem 21:44] João Paulo Luís
    
Se o Tiago José Torres Venceslau quiser rever o https://github.com/PharmaLedger-IMI/fgt-workspace/commit/b2831b443b0c2b1207e50887e20248192685175a
(Só interessa as alterações ao SimpleShipmentManager.js. O resto são burocracias...)

Estava com medo de:


	
as APIs de BD guardarem uma mensagem que é um objecto (em vez de uma string) darem asneira... mas isso não aconteceu nenhum erro nos testes...
	
as mensagens vão ficando grandes... cada vez que há mais shipmentLines e mais log nos estados... mas parece-me +/- contido
	
o objeto recebido é um JSON.parse(), Não tem a class SimpleShipment. (Isso é preciso ? Só para invocar validates, certo ?)


Se baixar muito o tempo de espera (ex: 100ms), dá o erro descrito no caso 1 em  https://github.com/PharmaLedger-IMI/fgt-workspace/issues/91#issuecomment-1190185035

(Não considero que esse erro seja crítico para já...)

Se baixar abaixo dos 5 segundos (+/-), dá o erro
----
http PUT {​​​​​​​​​​​​"path":"/traceability/shipment/update/MAH136366355-16584360666938210708","method":"PUT","headers":{​​​​​​​​​​​​"content-type":"application/json","content-length":80,"Authorization":"Basic V0hTMDAwMDAxOlRoaXMxc1N1Y2hBUzNjdXJlUGFzc3cwcmQ="}​​​​​​​​​​​​,"hostname":"api-whs1.localhost","port":"8080"}​​​​​​​​​​​​ {​​​​​​​​​​​​"status":"received","extraInfo":"Received in good condition by a test script!"}​​​​​​​​​​​​
res 130ms {​​​​​​​​​​​​
  status: 400,
  error: 'Bad Request',
  message: [ 'Status update from pickup to received is not allowed' ]
}​​​​​​​​​​​​
---
porque é onde a API deixa de chamar /shipment/update no MAH, e passa a chamar /shipment/update no WHS... mas nesse caso deve ser repetível...

Mas julgo que 5 segundos já é difícil de reproduzir "à mão" smile
```

**Comment by joaoluis-pdm** [comment]
The problem is considered fixed for now.

A possible solution to overcome the problem 1 described in https://github.com/PharmaLedger-IMI/fgt-workspace/issues/91#issuecomment-1190185035 a possible solution would be to transform all REST invocations into messages (so that REST invocation are serialized into message processing). But that would present some difficulties:
- REST is synchronous and needs a synchronous reply, while messages are asynchronous.
- all messages go through the centralized "traceability" domain (mq server). So "local" REST invocations would no longer be "local" (within a single participant domain).
